[package]
name = "gild"
version = "0.1.0"
edition = "2024"

[dependencies]
buckle = { version = "*", git = "https://github.com/trunk-os/buckle" }
axum = "*"
axum-serde = { version = "*", features = [ "cbor" ] }
serde = { version = "*", features = [ "derive" ] }
serde_yaml_ng = "*"
anyhow = "*"
http = "*"
